using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.UI;

public class ToolsController : MonoBehaviour
{
    public GameObject Cursor;
    public int Rounding = 1;
    
    enum Tools { Wall, Room, Del, Cursor};
    Tools tools = Tools.Cursor;


    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
       
    }

    public void CursorOff()
    {
        Cursor.SetActive(false);
        tools = Tools.Cursor;
        WallCreate.mode = WallCreate.Mode.Cursor;
    }

    public void WallEdit()
    {
        Cursor.SetActive(true);
        WallCreate.mode = WallCreate.Mode.Wall;
    }


    public void RoomEdit()
    {
        Cursor.SetActive(true);
        WallCreate.mode = WallCreate.Mode.Room;
    }

    public void Delete()
    {
        tools = Tools.Del;
    }

}
