using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

public class TestDrawScript : MonoBehaviour
{
    void Start ()
    {
        DebugHelper.ActivateConsole();

        drawCanvas_ = GameObject.Find("DrawCanvas");
        //drawCanvas_.SetActive(false);

        controlCanvas_ = GameObject.Find("ControlCanvas");
        //controlCanvas_.SetActive(false);

        Debug.Log("Start");
    }

    void Update ()
    {
       /* var click = Input.GetKeyUp(KeyCode.Mouse0) &&
            EventSystem.current.IsPointerOverGameObject();

        if (click)
        {
            Debug.Log("click");
        }*/
    }

    private void OnGUI()
    {
        DebugHelper.DrawConsole();
    }

    GameObject drawCanvas_;
    GameObject controlCanvas_;
}
